var unfiltered = [{
        "id": 64,
        "xParent": 3,
        "NumChildren": 1,
        "inactive": "",
        "organization": "Reported",
        "name": "St. Johns - Dr. Kenneth Williams Health Center",
        "addr1": "808 W. 58th St.",
        "addr2": "Los Angeles, CA 90037",
        "vaccines": "p",
        "logo": "",
        "mapZoom": "https://www.google.com/maps/d/embed?mid=1AdIIUb669F7mV6J5A6McJo7eC5X67dfG&ll=33.989492599999984%2C-118.28768310000001&z=16",
        "notes": null,
        "notesSpn": "",
        "alt": "",
        "altSpn": "",
        "date": "",
        "time": "",
        "link": "",
        "secondDose": "",
        "full": "",
        "comments": "",
        "commentsSpn": "",
        "times": [],
        "clinicFormat": 1,
        "system": ""
    },
    {
        "id": "",
        "xParent": 64,
        "NumChildren": 999,
        "inactive": "",
        "organization": "Reported",
        "name": "",
        "addr1": "",
        "addr2": "",
        "vaccines": "",
        "logo": "",
        "mapZoom": "",
        "notes": "",
        "notesSpn": "",
        "alt": "",
        "altSpn": "",
        "date": "3/11/2021",
        "time": "5pm-7:30pm",
        "link": "https://www.calvax.org/reg/4712608929",
        "secondDose": "",
        "full": "full",
        "comments": "",
        "commentsSpn": "",
        "times": "",
        "clinicFormat": "",
        "system": ""
    },
    {
        "id": 67,
        "xParent": 3,
        "NumChildren": 1,
        "inactive": "",
        "organization": "Reported",
        "name": "St. Johns - Compton Health Center",
        "addr1": "2115 N. Wilmington Ave.",
        "addr2": "Compton, CA 90222",
        "vaccines": "p",
        "logo": "",
        "mapZoom": "https://www.google.com/maps/d/embed?mid=1AdIIUb669F7mV6J5A6McJo7eC5X67dfG&ll=33.91185609999999%2C-118.23943659999999&z=16",
        "notes": null,
        "notesSpn": "",
        "alt": "",
        "altSpn": "",
        "date": "",
        "time": "",
        "link": "",
        "secondDose": "",
        "full": "",
        "comments": "",
        "commentsSpn": "",
        "times": [],
        "clinicFormat": 1,
        "system": ""
    },
    {
        "id": "",
        "xParent": 67,
        "NumChildren": 999,
        "inactive": "",
        "organization": "Reported",
        "name": "",
        "addr1": "",
        "addr2": "",
        "vaccines": "",
        "logo": "",
        "mapZoom": "",
        "notes": "",
        "notesSpn": "",
        "alt": "",
        "altSpn": "",
        "date": "3/11/2021",
        "time": "5pm-7:30pm",
        "link": "https://www.calvax.org/reg/8962197170",
        "secondDose": "",
        "full": "full",
        "comments": "",
        "commentsSpn": "",
        "times": "",
        "clinicFormat": "",
        "system": ""
    },
    {
        "id": 321,
        "xParent": 3,
        "NumChildren": 2,
        "inactive": "",
        "organization": "Reported",
        "name": "St. Johns - Compton College",
        "addr1": "1111 Artesia Blvd.",
        "addr2": "Los Angles, CA, 90221",
        "vaccines": "p",
        "logo": "",
        "mapZoom": "https://www.google.com/maps/d/embed?mid=1AdIIUb669F7mV6J5A6McJo7eC5X67dfG&ll=33.87766629733093%2C-118.20978438699197&z=16",
        "notes": null,
        "notesSpn": "",
        "alt": "",
        "altSpn": "",
        "date": "",
        "time": "",
        "link": "",
        "secondDose": "",
        "full": "",
        "comments": "",
        "commentsSpn": "",
        "times": [],
        "clinicFormat": 1,
        "system": ""
    },
    {
        "id": "",
        "xParent": 321,
        "NumChildren": 999,
        "inactive": "",
        "organization": "Reported",
        "name": "",
        "addr1": "",
        "addr2": "",
        "vaccines": "",
        "logo": "",
        "mapZoom": "",
        "notes": "",
        "notesSpn": "",
        "alt": "",
        "altSpn": "",
        "date": "3/11/2021",
        "time": "8:30am-4:30pm",
        "link": "https://www.calvax.org/reg/3619129086",
        "secondDose": "",
        "full": "full",
        "comments": "",
        "commentsSpn": "",
        "times": "",
        "clinicFormat": "",
        "system": ""
    },
    {
        "id": "",
        "xParent": 70,
        "NumChildren": 999,
        "inactive": "",
        "organization": "Reported",
        "name": "",
        "addr1": "",
        "addr2": "",
        "vaccines": "",
        "logo": "",
        "mapZoom": "",
        "notes": "",
        "notesSpn": "",
        "alt": "",
        "altSpn": "",
        "date": "3/11/2021",
        "time": "5pm-7:30pm",
        "link": "https://www.calvax.org/reg/6019129738",
        "secondDose": "",
        "full": "full",
        "comments": "",
        "commentsSpn": "",
        "times": "",
        "clinicFormat": "",
        "system": ""
    },
    {
        "id": "",
        "xParent": 73,
        "NumChildren": "",
        "inactive": "",
        "organization": "Reported",
        "name": "",
        "addr1": "",
        "addr2": "",
        "vaccines": "",
        "logo": "",
        "mapZoom": "",
        "notes": "",
        "notesSpn": "",
        "alt": "",
        "altSpn": "",
        "date": "3/11/2021",
        "time": "9am-5pm",
        "link": "https://www.calvax.org/reg/2469940721",
        "secondDose": "",
        "full": "full",
        "comments": "",
        "commentsSpn": "",
        "times": "",
        "clinicFormat": "",
        "system": ""
    },
    {
        "id": "",
        "xParent": 73,
        "NumChildren": "",
        "inactive": "",
        "organization": "Reported",
        "name": "",
        "addr1": "",
        "addr2": "",
        "vaccines": "",
        "logo": "",
        "mapZoom": "",
        "notes": "",
        "notesSpn": "",
        "alt": "",
        "altSpn": "",
        "date": "3/11/2021",
        "time": "9am-5pm",
        "link": "https://www.calvax.org/reg/6009129991",
        "secondDose": "",
        "full": "full",
        "comments": "",
        "commentsSpn": "",
        "times": "",
        "clinicFormat": "",
        "system": ""
    },
    {
        "id": 300,
        "xParent": 3,
        "NumChildren": 2,
        "inactive": "",
        "organization": "Reported",
        "name": "St. John's Well Child and Family - Dominguez",
        "addr1": "15301 S. San Jose Ave.",
        "addr2": "Compton, CA 90221",
        "vaccines": "p",
        "logo": "",
        "mapZoom": "https://www.google.com/maps/d/embed?mid=1AdIIUb669F7mV6J5A6McJo7eC5X67dfG&ll=33.89400516280599%2C-118.18516678150635&z=16",
        "notes": null,
        "notesSpn": "",
        "alt": "",
        "altSpn": "",
        "date": "",
        "time": "",
        "link": "",
        "secondDose": "",
        "full": "",
        "comments": "",
        "commentsSpn": "",
        "times": [],
        "clinicFormat": 1,
        "system": ""
    },
    {
        "id": 301,
        "xParent": 3,
        "NumChildren": 2,
        "inactive": "",
        "organization": "Reported",
        "name": "St. John's Well Child and Family - Lincoln",
        "addr1": "2515 Alta St.",
        "addr2": "Los Angeles, CA 90031",
        "vaccines": "p",
        "logo": "",
        "mapZoom": "https://www.google.com/maps/d/embed?mid=1AdIIUb669F7mV6J5A6McJo7eC5X67dfG&ll=34.07641368453835%2C-118.20765048150638&z=16",
        "notes": null,
        "notesSpn": "",
        "alt": "",
        "altSpn": "",
        "date": "",
        "time": "",
        "link": "",
        "secondDose": "",
        "full": "",
        "comments": "",
        "commentsSpn": "",
        "times": [],
        "clinicFormat": 1,
        "system": ""
    },
    {
        "id": 302,
        "xParent": 3,
        "NumChildren": 2,
        "inactive": "",
        "organization": "Reported",
        "name": "St. John's Well Child and Family - Washington",
        "addr1": "1555 W 110th St.",
        "addr2": "Los Angeles, CA 90047",
        "vaccines": "p",
        "logo": "",
        "mapZoom": "https://www.google.com/maps/d/embed?mid=1AdIIUb669F7mV6J5A6McJo7eC5X67dfG&ll=33.93668565767807%2C-118.30818748150638&z=16",
        "notes": null,
        "notesSpn": "",
        "alt": "",
        "altSpn": "",
        "date": "",
        "time": "",
        "link": "",
        "secondDose": "",
        "full": "",
        "comments": "",
        "commentsSpn": "",
        "times": [],
        "clinicFormat": 1,
        "system": ""
    },
    {
        "id": 329,
        "xParent": 3,
        "NumChildren": 2,
        "inactive": "",
        "organization": "Reported",
        "name": "St. John's Well Child and Family - East LA Civic Center",
        "addr1": "4801 E. 3rd Street",
        "addr2": "Los Angeles, CA 90022",
        "vaccines": "p",
        "logo": "",
        "mapZoom": "https://www.google.com/maps/d/embed?mid=1AdIIUb669F7mV6J5A6McJo7eC5X67dfG&ll=34.03409310234569%2C-118.16067840233019&z=16",
        "notes": "East LA Residents only",
        "notesSpn": "Solo para residentes del este de Los Ángeles",
        "alt": "",
        "altSpn": "",
        "date": "",
        "time": "",
        "link": "",
        "secondDose": "",
        "full": "",
        "comments": "East LA Residents only",
        "commentsSpn": "Solo para residentes del este de Los Ángeles",
        "times": [],
        "clinicFormat": 1,
        "system": ""
    },
    {
        "id": "",
        "xParent": 329,
        "NumChildren": 999,
        "inactive": "",
        "organization": "Reported",
        "name": "",
        "addr1": "",
        "addr2": "",
        "vaccines": "",
        "logo": "",
        "mapZoom": "",
        "notes": "",
        "notesSpn": "",
        "alt": "",
        "altSpn": "",
        "date": "3/11/2021",
        "time": "9:30am-4:30pm",
        "link": "https://www.calvax.org/reg/9237601649",
        "secondDose": "",
        "full": "full",
        "comments": "",
        "commentsSpn": "",
        "times": "",
        "clinicFormat": "",
        "system": ""
    },
    {
        "id": 79,
        "xParent": 3,
        "NumChildren": 1,
        "inactive": "",
        "organization": "Reported",
        "name": "East Valley Community Health Center - Pomona",
        "addr1": "1555 S. Garey Ave.",
        "addr2": "Pomona, CA 91766",
        "vaccines": "m",
        "logo": "",
        "mapZoom": "https://www.google.com/maps/d/embed?mid=1AdIIUb669F7mV6J5A6McJo7eC5X67dfG&ll=34.04314070000003%2C-117.75044&z=16",
        "notes": null,
        "notesSpn": "",
        "alt": "",
        "altSpn": "",
        "date": "",
        "time": "",
        "link": "",
        "secondDose": "",
        "full": "",
        "comments": "",
        "commentsSpn": "",
        "times": [],
        "clinicFormat": 1,
        "system": ""
    },
    {
        "id": "",
        "xParent": 79,
        "NumChildren": "",
        "inactive": "",
        "organization": "Reported",
        "name": "",
        "addr1": "",
        "addr2": "",
        "vaccines": "",
        "logo": "",
        "mapZoom": "",
        "notes": "",
        "notesSpn": "",
        "alt": "",
        "altSpn": "",
        "date": "3/10/2021",
        "time": "8am-5pm",
        "link": "https://www.calvax.org/reg/4263913062",
        "secondDose": "",
        "full": "full",
        "comments": "",
        "commentsSpn": "",
        "times": "",
        "clinicFormat": "",
        "system": ""
    },
    {
        "id": 85,
        "xParent": 3,
        "NumChildren": 1,
        "inactive": "",
        "organization": "Reported",
        "name": "East Valley Community Health Center - Covina",
        "addr1": "276 W. College St.",
        "addr2": "Covina, CA 91723",
        "vaccines": "m",
        "logo": "",
        "mapZoom": "https://www.google.com/maps/d/embed?mid=1AdIIUb669F7mV6J5A6McJo7eC5X67dfG&ll=33.89299290000001%2C-118.2950049&z=15",
        "notes": null,
        "notesSpn": "",
        "alt": "",
        "altSpn": "",
        "date": "",
        "time": "",
        "link": "",
        "secondDose": "",
        "full": "",
        "comments": "",
        "commentsSpn": "",
        "times": [],
        "clinicFormat": 1,
        "system": ""
    },
    {
        "id": "",
        "xParent": 85,
        "NumChildren": "",
        "inactive": "",
        "organization": "Reported",
        "name": "",
        "addr1": "",
        "addr2": "",
        "vaccines": "",
        "logo": "",
        "mapZoom": "",
        "notes": "",
        "notesSpn": "",
        "alt": "",
        "altSpn": "",
        "date": "3/10/2021",
        "time": "8am-3pm",
        "link": "https://www.calvax.org/reg/0319162693",
        "secondDose": "",
        "full": "full",
        "comments": "",
        "commentsSpn": "",
        "times": "",
        "clinicFormat": "",
        "system": ""
    },
    {
        "id": 308,
        "xParent": 3,
        "NumChildren": 1,
        "inactive": "",
        "organization": "Reported",
        "name": "East Valley Community Health Center - La Puente",
        "addr1": "17840 Villa Corta St",
        "addr2": "La Puente, CA 91744",
        "vaccines": "m",
        "logo": "",
        "mapZoom": "https://www.google.com/maps/d/embed?mid=1AdIIUb669F7mV6J5A6McJo7eC5X67dfG&ll=34.01778533652456%2C-117.9186935630127&z=16",
        "notes": null,
        "notesSpn": "",
        "alt": "",
        "altSpn": "",
        "date": "",
        "time": "",
        "link": "",
        "secondDose": "",
        "full": "",
        "comments": "",
        "commentsSpn": "",
        "times": [],
        "clinicFormat": 1,
        "system": ""
    },
    {
        "id": "",
        "xParent": 308,
        "NumChildren": "",
        "inactive": "",
        "organization": "Reported",
        "name": "",
        "addr1": "",
        "addr2": "",
        "vaccines": "",
        "logo": "",
        "mapZoom": "",
        "notes": "",
        "notesSpn": "",
        "alt": "",
        "altSpn": "",
        "date": "3/10/2021",
        "time": "8:30am-3:45pm",
        "link": "",
        "secondDose": "https://www.calvax.org/reg/2078931699",
        "full": "full",
        "comments": "",
        "commentsSpn": "",
        "times": "",
        "clinicFormat": "",
        "system": ""
    },
    {
        "id": 95,
        "xParent": 3,
        "NumChildren": 6,
        "inactive": "",
        "organization": "Reported",
        "name": "Kedren Community Health Center",
        "addr1": "4211 S. Avalon",
        "addr2": "Los Angeles, CA 90011",
        "vaccines": "m",
        "logo": "",
        "mapZoom": "https://www.google.com/maps/d/embed?mid=1AdIIUb669F7mV6J5A6McJo7eC5X67dfG&ll=34.0073395%2C-118.26546379999999&z=16",
        "notes": null,
        "notesSpn": "",
        "alt": "",
        "altSpn": "",
        "date": "",
        "time": "",
        "link": "",
        "secondDose": "",
        "full": "",
        "comments": "This week, offering FIRST DOSE Moderna <em>or</em> Pfizer vaccine.  Second dose appointments are for Moderna only",
        "commentsSpn": "Esta semana, esta ubicación ofrecerá la PRIMERA DOSIS de la vacuna Moderna <em> o </em> vacuna Pfizer.  Las citas para la segunda dosis son solo para vacuna Moderna.",
        "times": [],
        "clinicFormat": 1,
        "system": ""
    },
    {
        "id": "",
        "xParent": 95,
        "NumChildren": 999,
        "inactive": "",
        "organization": "Reported",
        "name": "",
        "addr1": "",
        "addr2": "",
        "vaccines": "",
        "logo": "",
        "mapZoom": "",
        "notes": "",
        "notesSpn": "",
        "alt": "",
        "altSpn": "",
        "date": "3/10/2021",
        "time": "First Dose (Pfizer OR Moderna)",
        "link": "https://www.calvax.org/reg/1352939603",
        "secondDose": "",
        "full": "",
        "comments": "",
        "commentsSpn": "",
        "times": "",
        "clinicFormat": "",
        "system": ""
    },
    {
        "id": "",
        "xParent": 95,
        "NumChildren": 999,
        "inactive": "",
        "organization": "Reported",
        "name": "",
        "addr1": "",
        "addr2": "",
        "vaccines": "",
        "logo": "",
        "mapZoom": "",
        "notes": "",
        "notesSpn": "",
        "alt": "",
        "altSpn": "",
        "date": "3/10/2021",
        "time": "Second Dose (Moderna ONLY)",
        "link": "",
        "secondDose": "https://www.calvax.org/reg/3561303592",
        "full": "",
        "comments": "",
        "commentsSpn": "",
        "times": "",
        "clinicFormat": "",
        "system": ""
    },
    {
        "id": "",
        "xParent": 95,
        "NumChildren": 999,
        "inactive": "",
        "organization": "Reported",
        "name": "",
        "addr1": "",
        "addr2": "",
        "vaccines": "",
        "logo": "",
        "mapZoom": "",
        "notes": "",
        "notesSpn": "",
        "alt": "",
        "altSpn": "",
        "date": "3/11/2021",
        "time": "First Dose (Pfizer OR Moderna)",
        "link": "https://www.calvax.org/reg/3969380321",
        "secondDose": "",
        "full": "",
        "comments": "",
        "commentsSpn": "",
        "times": "",
        "clinicFormat": "",
        "system": ""
    },
    {
        "id": "",
        "xParent": 95,
        "NumChildren": 999,
        "inactive": "",
        "organization": "Reported",
        "name": "",
        "addr1": "",
        "addr2": "",
        "vaccines": "",
        "logo": "",
        "mapZoom": "",
        "notes": "",
        "notesSpn": "",
        "alt": "",
        "altSpn": "",
        "date": "3/11/2021",
        "time": "Second Dose (Moderna ONLY)",
        "link": "",
        "secondDose": "https://www.calvax.org/reg/3901630782",
        "full": "",
        "comments": "",
        "commentsSpn": "",
        "times": "",
        "clinicFormat": "",
        "system": ""
    },
    {
        "id": "",
        "xParent": 95,
        "NumChildren": 999,
        "inactive": "",
        "organization": "Reported",
        "name": "",
        "addr1": "",
        "addr2": "",
        "vaccines": "",
        "logo": "",
        "mapZoom": "",
        "notes": "",
        "notesSpn": "",
        "alt": "",
        "altSpn": "",
        "date": "3/12/2021",
        "time": "First Dose (Pfizer OR Moderna)",
        "link": "https://www.calvax.org/reg/0313462993",
        "secondDose": "",
        "full": "",
        "comments": "",
        "commentsSpn": "",
        "times": "",
        "clinicFormat": "",
        "system": ""
    },
    {
        "id": "",
        "xParent": 95,
        "NumChildren": 999,
        "inactive": "",
        "organization": "Reported",
        "name": "",
        "addr1": "",
        "addr2": "",
        "vaccines": "",
        "logo": "",
        "mapZoom": "",
        "notes": "",
        "notesSpn": "",
        "alt": "",
        "altSpn": "",
        "date": "3/12/2021",
        "time": "Second Dose (Moderna ONLY)",
        "link": "",
        "secondDose": "https://www.calvax.org/reg/3318296006",
        "full": "",
        "comments": "",
        "commentsSpn": "",
        "times": "",
        "clinicFormat": "",
        "system": ""
    },
    {
        "id": 303,
        "xParent": 3,
        "NumChildren": 1,
        "inactive": "",
        "organization": "Reported",
        "name": "CHA Hollywood Presbyterian Medical Center",
        "addr1": "1300 N Vermont Avenue",
        "addr2": "Los Angeles, CA 90027",
        "vaccines": "p",
        "logo": "",
        "mapZoom": "https://www.google.com/maps/d/embed?mid=1AdIIUb669F7mV6J5A6McJo7eC5X67dfG&ll=34.0968942856687%2C-118.29343108150634&z=16",
        "notes": "",
        "notesSpn": "",
        "alt": "",
        "altSpn": "",
        "date": "",
        "time": "",
        "link": "",
        "secondDose": "",
        "full": "",
        "comments": "<a target=\"_blank\" href=\"../../../docs/MapHPMC.pdf\">Grounds Map for Hollywood Presbyterian Medical Center</a>",
        "commentsSpn": "<a target=\"_blank\" href=\"../../../docs/MapHPMC.pdf\">Mapa de la puerta de Hollywood Presbyterian Medical Center</a>",
        "times": [],
        "clinicFormat": 2,
        "system": ""
    },
    {
        "id": "",
        "xParent": 303,
        "NumChildren": 999,
        "inactive": "",
        "organization": "Reported",
        "name": "",
        "addr1": "",
        "addr2": "",
        "vaccines": "",
        "logo": "",
        "mapZoom": "",
        "notes": "",
        "notesSpn": "",
        "alt": "",
        "altSpn": "",
        "date": "3/10/2021",
        "time": "8am-5pm",
        "link": "https://www.calvax.org/reg/5461303492",
        "secondDose": "",
        "full": "full",
        "comments": "",
        "commentsSpn": "",
        "times": "",
        "clinicFormat": "",
        "system": ""
    }
]